apiVersion: batch/v1
kind: CronJob
metadata:
  name: tpc-cron-run
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scheduled
              image: tp-centre-fpm:latest
              imagePullPolicy: Never
              envFrom:
                - configMapRef:
                    name: tp-centre
                - secretRef:
                    name: tp-centre
              command:
                - "php"
              args:
                - "artisan"
                - "schedule:run"
          restartPolicy: OnFailure
